### ISSUE TITLE
solution branch doesn't match the lab

### ISSUE THREAD

**Issue by cananz** [learn-co-curriculum/basic-nested-forms-lab#12]
solution branch is very out of date:
- has different view files than the lab gives students 
- the form created in solutions branch uses `fields_for` differently than what was taught in the [preceding readme lesson](https://github.com/learn-co-students/basic-nested-forms-dc-web-080519)
- has files that appear to be from a different lab. for example: 'app/controllers/posts_controller.rb'
- there are no routes created in 'config/routes.rb'

**Comment by sgharms** [comment]
Whew! This was all messed up. It is no longer! c44402f69f6 is the fix. Thanks!
