### ISSUE TITLE
The README and tests aren't aligned

### ISSUE THREAD

**Issue by coltonstaab1** [learn-co-curriculum/basic-nested-forms-lab#3]
Hey, so the tests for this lab require that you create a post/artist model that's completely separate from ingredient/recipe model that's referenced in the README. Combined with the fact that there's no solution to this lab, it's quite confusing

**Comment by AnnJohn** [comment]
hi @coltonstaab1 sorry about this. will look into this within the next two days. Thanks for raising the issue.

**Comment by c1505** [comment]
I am going through this lab now.  Deleting the post tests since it is pretty clear they don't belong.  If this gets updated and I should do something differently later, I will revisit it then.

**Comment by AnnJohn** [comment]
thanks @c1505. We definitely need to update this lab and will do so within the next couple of weeks.
