### ISSUE TITLE
Rails Console command non-functional for windows?

### ISSUE THREAD

**Issue by Kiveo** [learn-co-curriculum/basic-nested-forms-lab#7]
There seems to be an issue with the lesson where a Windows user will be unable to run rails console. The error message associated with running rails c or rails console mentions Spring loader.

Error Messages:
// ♥ rails c
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands/console.rb:29:in `block in parse_arguments': invalid option: -b (OptionParser::InvalidOption)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands/console.rb:15:in `new'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands/console.rb:15:in `parse_arguments'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:59:in `console'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /home/Kiveo/basic-nested-forms-lab-v-000/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'
Running via Spring preloader in process 686

**Comment by sgharms** [comment]
Hi there, this probably needs to be addressed via a 1/1 AAQ session. 

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).
