### ISSUE TITLE
After Forking, Does not show up as forked on Learn.co Page for this lab

### ISSUE THREAD

**Issue by kirbycampbell** [learn-co-curriculum/basic-nested-forms-lab#8]
After forking this isn't seeing the fork or progress being made.  Likely something is disconnected between learn.co and github on this specific lab page.
Thanks
*edit* - seems like it was fixed about 30 minutes after I made this flag.  Thanks!

**Comment by sgharms** [comment]
Thanks for pointing this out, even though it's old! Just now closing.
